# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_VP_test(object):
    def setupUi(self, VP_test):
        VP_test.setObjectName("VP_test")
        VP_test.resize(772, 666)
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        VP_test.setFont(font)
        self.LoadImg = QtWidgets.QPushButton(VP_test)
        self.LoadImg.setGeometry(QtCore.QRect(570, 220, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.LoadImg.setFont(font)
        self.LoadImg.setObjectName("LoadImg")
        self.LoadData = QtWidgets.QPushButton(VP_test)
        self.LoadData.setGeometry(QtCore.QRect(570, 290, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.LoadData.setFont(font)
        self.LoadData.setObjectName("LoadData")
        self.Start_Test = QtWidgets.QPushButton(VP_test)
        self.Start_Test.setGeometry(QtCore.QRect(570, 360, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Start_Test.setFont(font)
        self.Start_Test.setObjectName("Start_Test")
        self.VPTitleHint = QtWidgets.QPlainTextEdit(VP_test)
        self.VPTitleHint.setGeometry(QtCore.QRect(100, 50, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.VPTitleHint.setFont(font)
        self.VPTitleHint.setReadOnly(True)
        self.VPTitleHint.setBackgroundVisible(False)
        self.VPTitleHint.setObjectName("VPTitleHint")
        self.ChooseFolder = QtWidgets.QToolButton(VP_test)
        self.ChooseFolder.setGeometry(QtCore.QRect(540, 140, 201, 51))
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.ChooseFolder.setFont(font)
        self.ChooseFolder.setObjectName("ChooseFolder")
        self.TestInfo = QtWidgets.QListView(VP_test)
        self.TestInfo.setGeometry(QtCore.QRect(100, 180, 256, 192))
        self.TestInfo.setObjectName("TestInfo")
        self.Terminate = QtWidgets.QPushButton(VP_test)
        self.Terminate.setGeometry(QtCore.QRect(570, 430, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Terminate.setFont(font)
        self.Terminate.setObjectName("Terminate")
        self.QuitAndClose = QtWidgets.QPushButton(VP_test)
        self.QuitAndClose.setGeometry(QtCore.QRect(490, 610, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.QuitAndClose.setFont(font)
        self.QuitAndClose.setStyleSheet("font: 75 15pt \"Courier\"\n""rgb(239, 41, 41)")
        self.QuitAndClose.setObjectName("QuitAndClose")
        self.TestProgress = QtWidgets.QProgressBar(VP_test)
        self.TestProgress.setGeometry(QtCore.QRect(100, 380, 251, 23))
        self.TestProgress.setProperty("value", 0)
        self.TestProgress.setObjectName("TestProgress")

        self.retranslateUi(VP_test)
        self.QuitAndClose.clicked.connect(VP_test.deleteLater)
        self.Start_Test.clicked.connect(self.TestProgress.update)
        QtCore.QMetaObject.connectSlotsByName(VP_test)

    def retranslateUi(self, VP_test):
        _translate = QtCore.QCoreApplication.translate
        VP_test.setWindowTitle(_translate("VP_test", "Vision Chip Test"))
        self.LoadImg.setText(_translate("VP_test", "Load Image"))
        self.LoadData.setText(_translate("VP_test", "Load Data"))
        self.Start_Test.setText(_translate("VP_test", "Start Test"))
        self.VPTitleHint.setPlainText(_translate("VP_test", "Vision Chip Test"))
        self.ChooseFolder.setText(_translate("VP_test", "Choose Folder"))
        self.Terminate.setText(_translate("VP_test", "Terminate"))
        self.QuitAndClose.setText(_translate("VP_test", "Quit Test and Exit"))

if __name__=="__main__":
    import sys
    from PyQt5.QtGui import QIcon
    app=QtWidgets.QApplication(sys.argv)
    widget=QtWidgets.QWidget()
    ui=Ui_VP_test()
    ui.setupUi(widget)
    widget.setWindowIcon(QIcon('web.png'))
    widget.show()
    sys.exit(app.exec_())